# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings
import opal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opal', '0028_auto_20170210_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('provisional', models.BooleanField(verbose_name='Suspected?', default=False, help_text='True if the allergy is only suspected. Defaults to False.')),
                ('details', models.CharField(max_length=255, blank=True)),
                ('drug_ft', models.CharField(max_length=255, blank=True, null=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, related_name='created_tuong_clinic_allergies_subrecords', to=settings.AUTH_USER_MODEL)),
                ('drug_fk', models.ForeignKey(blank=True, null=True, to='opal.Drug')),
                ('patient', models.ForeignKey(to='opal.Patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, related_name='updated_tuong_clinic_allergies_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('hospital_number', models.CharField(max_length=255, blank=True, help_text='The unique identifier for this patient at the hospital.')),
                ('nhs_number', models.CharField(verbose_name='NHS Number', max_length=255, blank=True, null=True)),
                ('surname', models.CharField(max_length=255, blank=True)),
                ('first_name', models.CharField(max_length=255, blank=True)),
                ('middle_name', models.CharField(max_length=255, blank=True, null=True)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth', blank=True, null=True)),
                ('religion', models.CharField(max_length=255, blank=True, null=True)),
                ('date_of_death', models.DateField(verbose_name='Date of Death', blank=True, null=True)),
                ('post_code', models.CharField(max_length=20, blank=True, null=True)),
                ('gp_practice_code', models.CharField(verbose_name='GP Practice Code', max_length=20, blank=True, null=True)),
                ('death_indicator', models.BooleanField(default=False, help_text='This field will be True if the patient is deceased.')),
                ('title_ft', models.CharField(max_length=255, blank=True, null=True, default='')),
                ('marital_status_ft', models.CharField(max_length=255, blank=True, null=True, default='')),
                ('birth_place_ft', models.CharField(max_length=255, blank=True, null=True, default='')),
                ('ethnicity_ft', models.CharField(max_length=255, blank=True, null=True, default='')),
                ('sex_ft', models.CharField(max_length=255, blank=True, null=True, default='')),
                ('birth_place_fk', models.ForeignKey(blank=True, null=True, to='opal.Destination')),
                ('created_by', models.ForeignKey(blank=True, null=True, related_name='created_tuong_clinic_demographics_subrecords', to=settings.AUTH_USER_MODEL)),
                ('ethnicity_fk', models.ForeignKey(blank=True, null=True, to='opal.Ethnicity')),
                ('marital_status_fk', models.ForeignKey(blank=True, null=True, to='opal.MaritalStatus')),
                ('patient', models.ForeignKey(to='opal.Patient')),
                ('sex_fk', models.ForeignKey(blank=True, null=True, to='opal.Gender')),
                ('title_fk', models.ForeignKey(blank=True, null=True, to='opal.Title')),
                ('updated_by', models.ForeignKey(blank=True, null=True, related_name='updated_tuong_clinic_demographics_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('provisional', models.BooleanField(verbose_name='Provisional?', default=False, help_text='True if the diagnosis is provisional. Defaults to False')),
                ('details', models.CharField(max_length=255, blank=True)),
                ('date_of_diagnosis', models.DateField(blank=True, null=True)),
                ('condition_ft', models.CharField(max_length=255, blank=True, null=True, default='')),
                ('condition_fk', models.ForeignKey(blank=True, null=True, to='opal.Condition')),
                ('created_by', models.ForeignKey(blank=True, null=True, related_name='created_tuong_clinic_diagnosis_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, related_name='updated_tuong_clinic_diagnosis_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('test', models.CharField(max_length=255)),
                ('date_ordered', models.DateField(blank=True, null=True)),
                ('details', models.CharField(max_length=255, blank=True)),
                ('microscopy', models.CharField(max_length=255, blank=True)),
                ('organism', models.CharField(max_length=255, blank=True)),
                ('sensitive_antibiotics', models.CharField(max_length=255, blank=True)),
                ('resistant_antibiotics', models.CharField(max_length=255, blank=True)),
                ('result', models.CharField(max_length=255, blank=True)),
                ('igm', models.CharField(max_length=20, blank=True)),
                ('igg', models.CharField(max_length=20, blank=True)),
                ('vca_igm', models.CharField(max_length=20, blank=True)),
                ('vca_igg', models.CharField(max_length=20, blank=True)),
                ('ebna_igg', models.CharField(max_length=20, blank=True)),
                ('hbsag', models.CharField(max_length=20, blank=True)),
                ('anti_hbs', models.CharField(max_length=20, blank=True)),
                ('anti_hbcore_igm', models.CharField(max_length=20, blank=True)),
                ('anti_hbcore_igg', models.CharField(max_length=20, blank=True)),
                ('rpr', models.CharField(max_length=20, blank=True)),
                ('tppa', models.CharField(max_length=20, blank=True)),
                ('viral_load', models.CharField(max_length=20, blank=True)),
                ('parasitaemia', models.CharField(max_length=20, blank=True)),
                ('hsv', models.CharField(max_length=20, blank=True)),
                ('vzv', models.CharField(max_length=20, blank=True)),
                ('syphilis', models.CharField(max_length=20, blank=True)),
                ('c_difficile_antigen', models.CharField(max_length=20, blank=True)),
                ('c_difficile_toxin', models.CharField(max_length=20, blank=True)),
                ('species', models.CharField(max_length=20, blank=True)),
                ('hsv_1', models.CharField(max_length=20, blank=True)),
                ('hsv_2', models.CharField(max_length=20, blank=True)),
                ('enterovirus', models.CharField(max_length=20, blank=True)),
                ('cmv', models.CharField(max_length=20, blank=True)),
                ('ebv', models.CharField(max_length=20, blank=True)),
                ('influenza_a', models.CharField(max_length=20, blank=True)),
                ('influenza_b', models.CharField(max_length=20, blank=True)),
                ('parainfluenza', models.CharField(max_length=20, blank=True)),
                ('metapneumovirus', models.CharField(max_length=20, blank=True)),
                ('rsv', models.CharField(max_length=20, blank=True)),
                ('adenovirus', models.CharField(max_length=20, blank=True)),
                ('norovirus', models.CharField(max_length=20, blank=True)),
                ('rotavirus', models.CharField(max_length=20, blank=True)),
                ('giardia', models.CharField(max_length=20, blank=True)),
                ('entamoeba_histolytica', models.CharField(max_length=20, blank=True)),
                ('cryptosporidium', models.CharField(max_length=20, blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, related_name='created_tuong_clinic_investigation_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, related_name='updated_tuong_clinic_investigation_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('category', models.CharField(max_length=255, blank=True)),
                ('hospital', models.CharField(max_length=255, blank=True)),
                ('ward', models.CharField(max_length=255, blank=True)),
                ('bed', models.CharField(max_length=255, blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, related_name='created_tuong_clinic_location_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, related_name='updated_tuong_clinic_location_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PastMedicalHistory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('year', models.CharField(max_length=4, blank=True)),
                ('details', models.CharField(max_length=255, blank=True)),
                ('condition_ft', models.CharField(max_length=255, blank=True, null=True, default='')),
                ('condition_fk', models.ForeignKey(blank=True, null=True, to='opal.Condition')),
                ('created_by', models.ForeignKey(blank=True, null=True, related_name='created_tuong_clinic_pastmedicalhistory_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(to='opal.Episode')),
                ('updated_by', models.ForeignKey(blank=True, null=True, related_name='updated_tuong_clinic_pastmedicalhistory_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PatientConsultation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('initials', models.CharField(max_length=255, blank=True, help_text='The initials of the user who gave the consult.')),
                ('discussion', models.TextField(blank=True)),
                ('reason_for_interaction_ft', models.CharField(max_length=255, blank=True, null=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, related_name='created_tuong_clinic_patientconsultation_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(to='opal.Episode')),
                ('reason_for_interaction_fk', models.ForeignKey(blank=True, null=True, to='opal.PatientConsultationReasonForInteraction')),
                ('updated_by', models.ForeignKey(blank=True, null=True, related_name='updated_tuong_clinic_patientconsultation_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SymptomComplex',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('duration', models.CharField(max_length=255, blank=True, null=True, choices=[('3 days or less', '3 days or less'), ('4-10 days', '4-10 days'), ('11-21 days', '11-21 days'), ('22 days to 3 months', '22 days to 3 months'), ('over 3 months', 'over 3 months')], help_text='The duration for which the patient had been experiencing these symptoms when recorded.')),
                ('details', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, related_name='created_tuong_clinic_symptomcomplex_subrecords', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(to='opal.Episode')),
                ('symptoms', models.ManyToManyField(blank=True, related_name='symptoms', to='opal.Symptom')),
                ('updated_by', models.ForeignKey(blank=True, null=True, related_name='updated_tuong_clinic_symptomcomplex_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('consistency_token', models.CharField(max_length=8)),
                ('dose', models.CharField(max_length=255, blank=True)),
                ('start_date', models.DateField(blank=True, null=True, help_text='The date on which the patient began receiving this treatment.')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('drug_ft', models.CharField(max_length=255, blank=True, null=True, default='')),
                ('route_ft', models.CharField(max_length=255, blank=True, null=True, default='')),
                ('frequency_ft', models.CharField(max_length=255, blank=True, null=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, related_name='created_tuong_clinic_treatment_subrecords', to=settings.AUTH_USER_MODEL)),
                ('drug_fk', models.ForeignKey(blank=True, null=True, to='opal.Drug')),
                ('episode', models.ForeignKey(to='opal.Episode')),
                ('frequency_fk', models.ForeignKey(blank=True, null=True, to='opal.Drugfreq')),
                ('route_fk', models.ForeignKey(blank=True, null=True, to='opal.Drugroute')),
                ('updated_by', models.ForeignKey(blank=True, null=True, related_name='updated_tuong_clinic_treatment_subrecords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(opal.models.UpdatesFromDictMixin, opal.models.ToDictMixin, models.Model),
        ),
    ]
